_base_: config.yaml

abci_group: "gxxNNNNN"

cluster:
    _target_: distributed.Client
    address:
      _target_: dask_jobqueue.PBSCluster
      n_workers: 1
      processes: 8
      queue: "rt_HF"
      resource_spec: "select=1"
      job_extra_directives: ["-P ${abci_group}", "-j oe", "-k oed"]
      cores: 96
      memory: "1000GB"
      local_directory: "$TMPDIR"
      walltime: "02:00:00"
      scheduler_options: {interface: "ibn2"}
      job_script_prologue:
        - "cd $PBS_O_WORKDIR"
        - "module load cuda/12.6/12.6.1"
        - "module load python/3.13/3.13.2"
        - "source PATH_TO_ENV/bin/activate"
