_base_: ${resolve_pkg_path:aiaccel.hpo.apps.config}/default.yaml

params:
  _convert_: partial
  _target_: aiaccel.hpo.optuna.hparams_manager.HparamsManager
  lr:
    _target_: aiaccel.hpo.optuna.hparams.Float
    low: 1.e-6
    high: 1.e-2
    log: true

n_trials: 1
n_max_jobs: 1
