micro_model: FL1-1
macro_model: FS1-1
scenarios: 2
agent_sizes:
  naive: 1
  rational: 0
  ruby: 0
trials:
  micro: 2
  macro_train: 2
  macro_test: 2
seeds:
  micro: 0
  macro_train: 0
  macro_test: 0
samplers:
  micro: random
  macro_train: cmaes
  macro_test: cmaes
scaling:
  sigma_scale: [97.0, 3.0]
  mu_scale: 300.0
  pi_complement: true
mas_bench_jar: ./work/tmp/MAS-Bench.jar
dataset_root: ./work/tmp/masbench-resources/Dataset
allow_mock: false
output_root: ./work/modelbridge/data_assimilation