search_range:
  kernel_size: [3,5]
  base_layer_num: [1,2,3,4,3,3,1]
  layer_search_range: [-1,0,1]
  base_filter_size: [16,24,32,64,96,160,320]
  filter_size_search_ratio: [0.75, 1.0, 1.25]
  conv_ops: ["Conv", "SepConv", "MBConv"]
  expansion_ratio: [3,6]
  skip_ops: ["no_skip", "skip"]
  se_ratio: [0, 0.25]

settings:
  class_num: 1000
  strides: [1,2,2,2,1,2,1]
  first_conv_filter_size: 32
  last_ch: 1280
