environment:
  result_dir: ./architecture_search_results  # A path to directory where search results are saved.
  device_ids: [0, 1, 2, 3]  # Indices of GPU for parallel processing.
  num_workers: 9  # The number of workers for dataloader.
  gpus: null # The number of GPUs


dataset:
  name: cifar10  # imagenet or cifar10 or cifar100
  path: ../data
  num_search_classes: 10  # The number of data classes for supernet train and architecture search.
  num_data_architecture_search: 10000  # The number of data for architecture search. Others are used in supernet train.

nas:
  search_space: proxyless
  num_epochs_supernet_train: 2 #60
  num_epochs_architecture_search: 2 #60
  seed: 42

trainer:
  strategy: ddp_find_unused_parameters_true
  enable_progress_bar: false
  logger: false
  enable_model_summary: false