generic:
  workspace: "./work"
  job_command: "python user.py"
  batch_job_timeout: 600

resource:
  type: "local"
  num_node: 1

ABCI:
  group: "[group]"
  job_script_preamble: "./job_script_preamble.sh"
  job_execution_options: ""

optimize:
  search_algorithm: "grid"
  goal: "minimize"
  trial_number: 1
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: 0.0
      upper: 5.0
      step: 1.0
      log: false
      base: 10
    -
      name: "x2"
      type: "uniform_float"
      lower: 0.0
      upper: 5.0
      step: 1.0
      log: false
      base: 10
