generic:
  workspace: "./work"
  job_command: "python user.py"
  batch_job_timeout: 600

resource:
  type: "local"
  num_node: 4

ABCI:
  group: "[group]"
  job_script_preamble: "./job_script_preamble.sh"
  job_execution_options: ""

optimize:
  search_algorithm: "NelderMeadOptimizer"
  #search_algorithm: "RandomOptimizer"
  #search_algorithm: "SobolOptimizer"
  #search_algorithm: "GridOptimizer"
  #search_algorithm: "TpeOptimizer"
  goal: "minimize"
  trial_number: 30
  rand_seed: 42
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: 0.0
    -
      name: "x2"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: 0.0
    -
      name: "x3"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: 0.0
    -
      name: "x4"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: 0.0
    -
      name: "x5"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: 0.0
