generic:
  workspace: "./work"
  job_command: "python user.py"
  batch_job_timeout: 600

resource:
  type: "local"
  num_node: 4

ABCI:
  group: "[group]"
  job_script_preamble: "./job_script_preamble.sh"
  job_execution_options: ""

optimize:
  search_algorithm: "nelder-mead"
  goal: "minimize"
  trial_number: 30
  rand_seed: 42
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: [0.74,  1.69,  1.22,  2.09, -3.24, -3.58]
    -
      name: "x2"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: [2.98,  2.27,  1.41, -2.10, -3.29, -0.35]
    -
      name: "x3"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: [3.62,  4.38, -0.40,  2.94,  2.23, -3.07]
    -
      name: "x4"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: [0.90,  2.00,  4.29, -1.43, -4.02,  2.25]
    -
      name: "x5"
      type: "uniform_float"
      lower: -5.0
      upper: 5.0
      initial: [1.99,  3.90,  3.10,  0.06, -3.83,  1.16]
