name: Publish on GitHub Pages

on:
  [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev,github-actions,test]
      - name: Sphinx build
        run: |
          sphinx-apidoc -f -o docs/source/ ./aiaccel
          cd docs
          make gettext
          sphinx-intl update -p build/gettext -l en -l ja
      - name: Sphinx build
        run: |
          sphinx-build docs/source/ _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature/gh-pages' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build
          force_orphan: true